### ISSUE TITLE
empty protein, or no valid complete residues

### ISSUE THREAD

**Issue by connor-circle** [cmbi/dssp#10]
this is my pdb format：
ATOM      1  N   ASP A   1      63.210  21.960 131.820  1.00  0.00           N
ATOM      2  HT1 ASP A   1      64.020  22.090 132.450  1.00  0.00           H
ATOM      3  HT2 ASP A   1      63.160  20.960 131.520  1.00  0.00           H
ATOM      4  HT3 ASP A   1      62.360  22.160 132.380  1.00  0.00           H
ATOM      5  CA  ASP A   1      63.150  22.770 130.580  1.00  0.00           C
ATOM      6  HA  ASP A   1      64.130  22.970 130.160  1.00  0.00           H
ATOM      7  CB  ASP A   1      62.410  21.990 129.410  1.00  0.00           C
ATOM      8  HB1 ASP A   1      62.120  22.760 128.660  1.00  0.00           H
ATOM      9  HB2 ASP A   1      61.520  21.520 129.870  1.00  0.00           H
ATOM     10  CG  ASP A   1      63.320  21.030 128.700  1.00  0.00           C
ATOM     11  OD1 ASP A   1      64.520  20.810 129.070  1.00  0.00           O
ATOM     12  OD2 ASP A   1      62.850  20.540 127.630  1.00  0.00           O
ATOM     13  C   ASP A   1      62.590  24.130 130.890  1.00  0.00           C
ATOM     14  O   ASP A   1      63.230  25.160 131.110  1.00  0.00           O
I use  [gmx trjconv -dump] to generate this pdb file . What are the problems of my pdb file?

**Comment by cbaakman** [comment]
The column numbers are wrong. Atom number, atom  name, etc. should always be on fixed columns.

Please check the PDB format description:
https://zhanglab.ccmb.med.umich.edu/SSIPe/pdb_atom_format.html#ATOM
