### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by liuyujie714** [cmbi/dssp#11]
`empty protein, or no valid complete residues`

https://github.com/cmbi/dssp/blob/master/src/structure.cpp#L1211

< 80 maybe wrong? Generally column length of PDB is 78, such as gmx trjconv -o xxx.pdb.
I remember old dssp 2.0.4 source code have not this judgement condition.

**Comment by cbaakman** [comment]
Dear user, please use the latest version of DSSP from here:
https://github.com/PDB-REDO/dssp

Also, when reporting a problem, it usually helps telling which PDB entry you use as input. "Empty protein" is a very entry-specific error message.
