### ISSUE TITLE
Compatibility with Concoord

### ISSUE THREAD

**Issue by TomUnter** [cmbi/dssp#13]
Hi, thanks for maintaining dssp.
I would like to use dssp together with concoord to increase the structures created since it is heavily dependent on it.
But with the xssp version of dssp it returns: bad lexical cast: source type value could not be interpreted as target
With the standalone dssp: empty protein, or no valid complete residues

Would you happen to know what the problem is, since older versions, that I cannot find should have worked

**Comment by cbaakman** [comment]
Dear user, this repo of dssp is outdated. Please use: https://github.com/PDB-REDO/dssp
