### ISSUE TITLE
inconsistent release tag and filename

### ISSUE THREAD

**Issue by reneeotten** [cmbi/dssp#2]
The version released yesterday is tagged and listed as version ```3.1.2``` (also in ```configure.ac```). The file one would download is however from ```https://github.com/cmbi/dssp/releases/download/3.1.2/dssp-3.0.11.tar.gz```; so the correct directory, but the wrong version in the filename. This isn't ideal for downstream packagers - can you please correct the version in the filename?

**Comment by cbaakman** [comment]
Sorry, my bad! I replaced the file.
