### ISSUE TITLE
hydrogen skipping

### ISSUE THREAD

**Issue by kad-ecoli** [cmbi/dssp#4]
In PDB file, ATOM/HETATM for hydrogen will be (incorrectly) read in if there is no element type at the end of line. See pull request for fix:
https://github.com/cmbi/dssp/pull/3

**Comment by cbaakman** [comment]
I've read the ATOM line description at http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM

For as far as I understand, the element symbol should always be present in the ATOM/HETATM lines of a PDB file. Do you have an example of a pdb entry that doesn't have element symbols?

**Comment by kad-ecoli** [comment]
PDB files in the PDB database always contains element symbols. However, many Bioinformatics programs does not generate PDB files with element symbol.

For example, the [PDB library (1.4GB)](https://zhanglab.ccmb.med.umich.edu/library/PDB.tar.bz2) used by [I-TASSER](https://zhanglab.ccmb.med.umich.edu/library/PDB.tar.bz2) only has 54 characters per "ATOM" line. [PULCHRA](http://www.pirx.com/pulchra/index.shtml), a commonly used program for reconstructing full atomic coordinate from CA atoms, also only keep 54 characters per "ATOM" line.

Almost every mainstream molecular graphic system (PyMOL, VMD, Jmol, RasMol) can correctly parse these PDB. Therefore, dssp should also support the parsing of this kind of PDB file as well.

**Comment by cbaakman** [comment]
I'll discuss this with the staff. To be continued..

**Comment by cbaakman** [comment]
@kad-ecoli 
We've decided that we'll handle this problem in a different way:

The next version of the mkdssp executable will ignore all ATOM/HETATM records that have 
only 54 characters. Thus the element symbol will become mandatory.

For people who wish to use the I-TASSER format, you should build software to convert to the wwpdb standard and maintain it in your own repository. Thus it will become your responsibility.

Thank you for pointing this out!

**Comment by cbaakman** [comment]
Closing this in favor of https://github.com/cmbi/dssp/commit/7574c67d6dac2eb0c37255310f7e70090c5a641c
