### ISSUE TITLE
New Version of DSSP not conpatible with martinize.py

### ISSUE THREAD

**Issue by JakeTheGreater** [cmbi/dssp#5]
The newest version of DSSP (3.1.2) is not compatible with the martinize.py script used for MARTINI coarse grained molecular dynamics. The standard output of DSSP is not compatible with the rest of the script. With this there is no secondary structure comparison and the script crashes.

"IOError: [Errno 2] No such file or directory: 'chain_A.ssd'"

This was not an issue with DSSP version 2.0.4. However the source code for this version is no longer available online.

**Comment by cbaakman** [comment]
The new dssp files should be backwards compatible with version 2, meaning they contain the same columns as the old files, plus extra columns. If this is not the case, then I'd like to know where to get this script you are running, what commands you use and which PDB/mmCIF file you are using.

The older DSSP software contains bugs and should not be used, though you might be able to find it here: https://github.com/cmbi/hssp/tree/9c4246f8d24ff1c08685148d55a6e69444d02776

**Comment by prateekbansal97** [comment]
Hello, 
I am facing a similar issue, when I am trying to use a dssp file generated by the (https://www3.cmbi.umcn.nl/xssp/) web server for the martinize.py script. Here is the script, which I downloaded from http://cgmartini.nl/images/tools/martinize/python3/martinize-2.6/martinize.py. I have attached the PDB file I am using as well, for reference. (I had to reformat it as a .txt file for it to be uploaded). Any help would be very appreciated, thank you!
[Prot.txt](https://github.com/cmbi/dssp/files/5344949/Prot.txt)

**Comment by cbaakman** [comment]
> Hello,
> I am facing a similar issue, when I am trying to use a dssp file generated by the (https://www3.cmbi.umcn.nl/xssp/) web server for the martinize.py script. Here is the script, which I downloaded from http://cgmartini.nl/images/tools/martinize/python3/martinize-2.6/martinize.py. I have attached the PDB file I am using as well, for reference. (I had to reformat it as a .txt file for it to be uploaded). Any help would be very appreciated, thank you!
> [Prot.txt](https://github.com/cmbi/dssp/files/5344949/Prot.txt)

I was able to create the dssp file from your pdb file using mkdssp 3.1.4. 
[prot.txt](https://github.com/cmbi/dssp/files/5345981/prot.txt)

Are you sure you're using the latest executable?

**Comment by prateekbansal97** [comment]
Hello, 

The issue is resolved now. I apologize for the delayed response. Thank You!
