### ISSUE TITLE
Question: How often is the local DSSP database updated?

### ISSUE THREAD

**Issue by joaomcteixeira** [cmbi/dssp#7]
How often is the local DSSP database updated? -> https://swift.cmbi.umcn.nl/gv/dssp/

Thanks you,

**Comment by cbaakman** [comment]
Hello, sorry for my late response. There's no database at swift. I think you mean the ftp repository: ftp://ftp.cmbi.umcn.nl/pub/molbio/data/dssp/

This databank is updated weekly. However, only new pdb entries are added. The update script does not review dssp entries that were already there.

**Comment by joaomcteixeira** [comment]
Hi @cbaakman , thanks very much for your response, I will keep that in mind.  :+1:
