### ISSUE TITLE
Missing residue from mkdssp output

### ISSUE THREAD

**Issue by antoinekoehl** [cmbi/dssp#9]
When I run mkdssp on PDB ID 2OB3, the output for chain A only goes to R 363 and misses the terminal A 364. I'm not sure if this is a known bug, or relates to an unusual termination of the chain with the final oxygen being named OXT instead of O.

**Comment by antoinekoehl** [comment]
Renaming the OXT to O in the pdb file fixed this error. I'm not sure how many PDB files have this unconventional termination.

**Comment by cbaakman** [comment]
Normally, the C-terminating residue contains two oxygen atoms in the backbone: O and OXT. Both are supposed to be there.
Because the O is missing, mkdssp doesn't consider the backbone complete and cannot derive secondary structure from it.

**Comment by antoinekoehl** [comment]
Thanks for the quick reply! It seems like that convention is not as popular in more recent structure that only have the O and then a TER card. Your explanation makes sense though!

**Comment by cbaakman** [comment]
Actually, the O is expected and the OXT is optional. Because the OXT atom is only encountered when the actual terminating residue is in the PDB file.

**Comment by cbaakman** [comment]
I discussed this with dr. Gert Vriend. Here's his answer:

```
We have realized that several refinement softwares recently have introduced bugs in the section that deals with termini. We observe that often 1 terminal O is missing. 

Sometimes this is scientifically justified, for example when the terminus is rather mobile (high B-factors) but the O makes a weak H-bond that gets its fit to the density just below the cutoff but the OXT does not have any restrictions so that its fit to the density gets above the cutoff.  But sometimes it is just a bug. In the latter case, it makes sense to look at the corresponding PDB_REDO file.




The DSSP problem is that it does not use partial residues. So if one of the C-terminal atoms is missing, DSSP skips the entire C-terminal residue because it is incomplete. This is perhaps a bit inconvenient. We might consider adding the missing terminal oxygen by modelling just before calculating the DSSP file... But that is the future...
```
